### ISSUE TITLE
package not found when installing with yarn 4

### ISSUE THREAD

**Issue by efstathiosntonas** [JasonCareter/fast-mlkit-translate-text#1]
```
➤ YN0000: · Yarn 4.1.0
➤ YN0000: ┌ Resolution step
➤ YN0035: │ ast-mlkit-translate-text@npm:1.0.0: Package not found
```

It's not published on npmjs yet: 
https://www.npmjs.com/search?q=fast-mlkit-translate-text

temp solution with yarn 4: `yarn add fast-mlkit-translate-text@https://github.com/yaaliuzhipeng/fast-mlkit-translate-text `

**Comment by JasonCareter** [comment]
sry, forgot to publish it to NPM 😂 fixed!
