### ISSUE TITLE
android compile error

### ISSUE THREAD

**Issue by ln613** [JasonCareter/fast-mlkit-translate-text#3]
I used the command "npx react-native@latest init translateML" to create a react-native project and run it in Android Studio without an issue (connect to a AVD with API 33). After I install "npm i --save fast-mlkit-translate-text" and try to rebuild with "npm run android", I got the following error:

`BUILD FAILED in 40s error Failed to install the app. Command failed with exit code 1: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081 C:\Code\rn\translateML\node_modules\fast-mlkit-translate-text\android\src\main\java\com\fastmlkittranslatetext\FastMlkitTranslateTextPackage.java:19: error: cannot find symbol if (name.equals(FastMlkitTranslateTextModule.NAME))  { ^ symbol: variable NAME location: class FastMlkitTranslateTextModule C:\Code\rn\translateML\node_modules\fast-mlkit-translate-text\android\src\main\java\com\fastmlkittranslatetext\FastMlkitTranslateTextPackage.java:32: error:  cannot find symbol FastMlkitTranslateTextModule.NAME, ^ symbol: variable NAME location: class FastMlkitTranslateTextModule C:\Code\rn\translateML\node_modules\fast-mlkit-translate-text\android\src\main\java\com\fastmlkittranslat etext\FastMlkitTranslateTextPackage.java:34: error: cannot find symbol FastMlkitTranslateTextModule.NAME, ^ symbol: variable NAME location: class FastMlkitTranslateTextModule C:\Code\rn\translateML\node_modules\fast-mlkit-transl ate-text\android\src\main\java\com\fastmlkittranslatetext\FastMlkitTranslateTextPackage.java:35: error: cannot find symbol FastMlkitTranslateTextModule.NAME, ^ symbol: variable NAME location: class FastMlkitTranslateTextModule N ote: C:\Code\rn\translateML\node_modules\fast-mlkit-translate-text\android\src\main\java\com\fastmlkittranslatetext\FastMlkitTranslateTextPackage.java uses or overrides a deprecated API. Note: Recompile with -Xlint:deprecation f or details. 4 errors FAILURE: Build failed with an exception. * What went wrong: Execution failed for task ':fast-mlkit-translate-text:compileDebugJavaWithJavac'. > Compilation failed; see the compiler error output for details. * Try: > Run with --info option to get more log output. > Run with --scan to get full insights. BUILD FAILED in 40s. info Run CLI with --verbose flag for more details.`

Looks like a version mismatch, any idea how I can fix it?

**Comment by JasonCareter** [comment]
I'll take a look

**Comment by JasonCareter** [comment]
this should be fixed in version 1.0.1, you can install it from npm now

**Comment by ln613** [comment]
fixed! Thanks!

**Comment by samwilcoxon** [comment]
This seems to be happening again in the latest React Native fyi @JasonCareter 

Mon, 14 Apr 2025 22:12:28 GMT

> Task :fast-mlkit-translate-text:compileDebugJavaWithJavac
Mon, 14 Apr 2025 22:12:28 GMT

/home/expo/workingdir/build/node_modules/fast-mlkit-translate-text/android/src/main/java/com/fastmlkittranslatetext/FastMlkitTranslateTextPackage.java:19: error: cannot find symbol
Mon, 14 Apr 2025 22:12:28 GMT

    if (name.equals(FastMlkitTranslateTextModule.NAME)) {
Mon, 14 Apr 2025 22:12:28 GMT

                                                ^
Mon, 14 Apr 2025 22:12:28 GMT

  symbol:   variable NAME
Mon, 14 Apr 2025 22:12:28 GMT

  location: class FastMlkitTranslateTextModule
Mon, 14 Apr 2025 22:12:28 GMT

/home/expo/workingdir/build/node_modules/fast-mlkit-translate-text/android/src/main/java/com/fastmlkittranslatetext/FastMlkitTranslateTextPackage.java:32: error: cannot find symbol
Mon, 14 Apr 2025 22:12:28 GMT

              FastMlkitTranslateTextModule.NAME,
Mon, 14 Apr 2025 22:12:28 GMT

                                          ^
Mon, 14 Apr 2025 22:12:28 GMT

  symbol:   variable NAME
Mon, 14 Apr 2025 22:12:28 GMT

  location: class FastMlkitTranslateTextModule
Mon, 14 Apr 2025 22:12:28 GMT

/home/expo/workingdir/build/node_modules/fast-mlkit-translate-text/android/src/main/java/com/fastmlkittranslatetext/FastMlkitTranslateTextPackage.java:34: error: cannot find symbol
Mon, 14 Apr 2025 22:12:28 GMT

                      FastMlkitTranslateTextModule.NAME,
Mon, 14 Apr 2025 22:12:28 GMT

                                                  ^
Mon, 14 Apr 2025 22:12:28 GMT

  symbol:   variable NAME
Mon, 14 Apr 2025 22:12:28 GMT

  location: class FastMlkitTranslateTextModule
Mon, 14 Apr 2025 22:12:28 GMT

/home/expo/workingdir/build/node_modules/fast-mlkit-translate-text/android/src/main/java/com/fastmlkittranslatetext/FastMlkitTranslateTextPackage.java:35: error: cannot find symbol
Mon, 14 Apr 2025 22:12:28 GMT

                      FastMlkitTranslateTextModule.NAME,
